version: '3.9'
services:
  database:
    image: 'mariadb:10.10.2'
    environment:
      - 'MYSQL_DATABASE=web-app'
      - 'MYSQL_ROOT_PASSWORD=password123'
    restart: 'unless-stopped'
    volumes:
      - './database/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '3306:3306'
  backend:
    build:
      context: backend
    deploy:
      restart_policy:
        delay: 15s
        condition: unless-stopped
    environment:
      - 'DB_HOST=database'
      - 'DB_PASSWORD=password123'
      - 'DB_NAME=web-app'
      - 'DB_USER=root'
    volumes:
      - ./backend/src:/app:ro
    ports:
      - '5000:5000'
  frontend:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/src:/app:ro
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
